version: '3.8'
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-server
    environment:
      - CHROMA_DB_IMPL=chromadb.db.impl.postgres.PostgresDB
      - CHROMA_DB_URL=postgresql://pillsure:pillsure123@host.docker.internal:5432/pillsure
      - ANONYMIZED_TELEMETRY=False
      - ALLOW_RESET=True
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped